# name: CI Pipeline

# on:
#     push:
#         branches: ['main']


# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     - name: Login to Dockerhub
#       env: 
#         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#         DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
#         IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/api:${{github.sha}}
#       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

#     - name: Build the Docker Image
#       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api .
#     - name: Push to DockerHub
#       run: docker push $IMAGE_NAME
